"""add circuit_price to seccurity

Revision ID: 96567468b771
Revises: 6ca6e554dc18
Create Date: 2026-08-25 21:30:42.211685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96567468b771'
down_revision: Union[str, Sequence[str], None] = '6ca6e554dc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circuit_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_column('circuit_price')

    # ### end Alembic commands ###
